services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "cutrungdang"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "Muadong@2025"
      - key: N8N_HOST
        value: cutrungdang.xyz
      - key: WEBHOOK_URL
        value: https://cutrungdang.xyz/
      - key: N8N_PROTOCOL
        value: https
